name: tttt_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_builder: ^0.7.0
  get: ^4.6.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  dropdown_button2: ^2.3.9
  cloud_firestore: ^4.9.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.1
  loading_animation_widget: ^1.2.0+4
  easy_stepper: ^0.8.1
  motion_toast: ^2.7.9
  intl: ^0.18.1
  file_picker: ^6.0.0
  http: ^1.1.0
  tiengviet: ^1.0.0
  syncfusion_flutter_pdf: ^23.1.44
  path_provider: ^2.1.1
  open_file: ^3.3.2
  universal_html: ^2.2.4
  syncfusion_flutter_xlsio: ^23.1.44

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
        # style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
